### ISSUE TITLE
Option to explicitly configure Calendar type (Gregorian/ISO/etc); Should use OS's locale

### ISSUE THREAD

**Issue by zenodotus280** [liamcain/obsidian-calendar-plugin#60]
2020 has 53 weeks but the plugin only shows 52. ISO 8601 has a convenient rule to determine the first week of the year: the first week containing a Thursday. 2021. Since January 1st is a Friday that means the first week must be the following one. 

I have tried updating to 1.4.1 but it fails under Obsidian 0.9.17

(apologies if this issue isn't written according to best practices, just wanted to get it out asap; I'm happy to be corrected)

**Comment by liamcain** [comment]
Hi @zenodotus280, looks like I messed up the release of 1.4.1 but it should be resolved now. As for your issue: I opted to use the the preferred week numbering based on locale. However, version 1.3.1 only had support for the `en-US` locale which uses 52 weeks.

In 1.4.0, I added support for additional locales so it should use the preferred week numbering system of your locale. Let me know if that resolves the issue for you!

**Comment by zenodotus280** [comment]
No luck. I switched my language to Swedish and I toggled the plugin, reloaded Obsidian, and so on in various combinations. I was in en-uk to begin with which should show 53 weeks.

**Comment by liamcain** [comment]
@zenodotus280 I should have clarified. I'm currently not reading the locale defined on the OS, just using the language you have selected within Obsidian in the "About" tab of settings. So the problem is that Obsidian only has en-US (not en-GB) and it doesn't look like it has Swedish as a language option yet. That's why you're still stuck in Gregorian week numbers.

I really wanted to avoid introducing more configuration but I think I might need to be a bit more flexible.

So I'll make the following changes:
- attempt to read the OS-level locale in addition to the Obsidian language setting.
- Add a dropdown for choosing between Gregorian and ISO for week numbering.

Thanks for the find, will try to have a fix for you soon!

**Comment by zenodotus280** [comment]
Very interesting - glad to be of help. It's an excellent plug-in.

**Comment by liamcain** [comment]
I should also mention that if you're using the weekly notes, if you use `WW` in your weekly format (instead of `ww`) the notes will use the ISO week numbering. So that way once I fix the display, your notes will still be in the correct place.

**Comment by liamcain** [comment]
So one thing I forgot to mention, the support for locales was only added to Obsidian in v0.9.18 (available to insiders). I just released v1.4.3 which which should improve the language and locale support in the calendar so once the new version of Obsidian is released (hopefully later today) this issue should be fixed. 

Please let me know if you're still having problems after that!

So re:plan outlined above:
- ~~attempt to read the OS-level locale in addition to the Obsidian language setting.~~
  - Done in v.1.4.3 of the calendar 
- Add a dropdown for choosing between Gregorian and ISO for week numbering.
  - Still TODO, but I'm not sure if it's still needed.

**Comment by zenodotus280** [comment]
0.9.18 was *just* released to everyone. Will be testing asap.

**Comment by zenodotus280** [comment]
![image](https://user-images.githubusercontent.com/16273022/101977609-6f9c1300-3c03-11eb-8866-ae92c832fd19.png)

Appears resolved in 0.9.10 / 1.4.4

**Comment by zenodotus280** [comment]
Unfortunately it seems the fix didn't last. I'm on 1.4.8 now and Week 1 is allegedly happening in a couple days.

**Comment by liamcain** [comment]
Great catch, it looks like Obsidian's behavior for setting the language/locale changed in the last few releases. Just pushed 1.4.9 which should fix it again.

I also added a new dropdown in settings to override the locale if you need to. Obsidian uses `en-US` by default, and we just started 2021 Week 1 today.

**Comment by Mpic** [comment]
Thanks for this fix !  
It's still not exactly there : W53 is correctly shown on Calendar view, but creating that weekly note tries to make a `2021-W53` that should be `2020-W53`.
![image](https://user-images.githubusercontent.com/5664276/103213716-d3665180-490e-11eb-996a-6836ab6b5fe5.png)

**Comment by liamcain** [comment]
@Mpic Great catch, this was because I had the wrong default for set for the weekly format. I have the default set to `YYYY-W[w]` in the settings. This should be `gggg-W[w]`. I released v1.4.10 to update the default but if you have anything custom in this field:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/693981/103220243-c6853600-48ed-11eb-86aa-1fe3ff5a04f8.png">

You'll want to make changes on your end.
